const inspirationRecipes = [
  {title:'Herb-crusted salmon', time:'30 min', tag:'Bright & fresh', image:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85', summary:'A bright, crisp-topped salmon dinner with tender greens and a lemony finish.'},
  {title:'Silky tomato pasta', time:'25 min', tag:'Vegetarian', image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85', summary:'A weeknight pasta that tastes like it simmered all afternoon.'},
  {title:'Lemony chicken traybake', time:'40 min', tag:'One pan', image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85', summary:'Golden chicken, roasted vegetables, and a bright lemon pan sauce.'},
  {title:'Crispy green fritters', time:'20 min', tag:'Vegetarian', image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85', summary:'Crisp-edged fritters with fresh herbs and a cool yogurt dip.'},
  {title:'Roasted vegetable grain bowl', time:'35 min', tag:'Bright & healthy', image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85', summary:'A colorful, make-it-your-own bowl for whatever the crisper holds.'},
  {title:'Garlicky mushroom toast', time:'15 min', tag:'Quick & easy', image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85', summary:'Buttery mushrooms and herbs piled high on good, crisp toast.'}
];
let recipes=[];
const defaultIngredients=['Salmon fillets','Fresh herbs','Lemon','Panko breadcrumbs','Tender greens','Olive oil'];
let pantry=['Salmon','Lemon','Fresh herbs','Baby spinach']; let savedRecipes=[]; let currentRecipe=recipes[0]; let photoDataUrl=''; let lastDish='';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function route(name){const target=$('#'+name);if(!target)return;$$('.view').forEach(v=>v.classList.remove('active'));target.classList.add('active');$$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));closeMenu();window.scrollTo({top:0,behavior:'smooth'});}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function renderPantry(){const list=$('#ingredients');list.innerHTML=pantry.map((item,i)=>`<span class="chip">${item}<button aria-label="Remove ${item}" data-remove="${i}">×</button></span>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{pantry.splice(+b.dataset.remove,1);renderPantry()})}
function recipeCard(recipe){const index=recipes.indexOf(recipe),image=recipe.image||inspirationRecipes[index%inspirationRecipes.length].image;return `<button class="recipe-card" data-recipe="${index}"><img src="${image}" alt="${escapeHtml(recipe.title)}"/><div class="card-info"><h3>${escapeHtml(recipe.title)}</h3><p><span>◷ ${escapeHtml(recipe.time)}</span><span>${escapeHtml(recipe.tag)}</span></p><small>${escapeHtml(recipe.matchReason||'')}</small></div></button>`}
function bindRecipeCards(container){container.querySelectorAll('[data-recipe]').forEach(card=>card.onclick=()=>openRecipe(recipes[+card.dataset.recipe]));}
function renderRecipes(items=recipes){const grid=$('#recipe-grid');if(!items.length){grid.innerHTML='<div class="empty-state"><span>✦</span><h3>No ingredient-only recipes yet.</h3><p>Add ingredients, then we’ll use OpenAI to create ideas from exactly what you have.</p></div>';return;}grid.innerHTML=items.map(recipeCard).join('');bindRecipeCards(grid);}
function renderSaved(){const grid=$('#saved-recipes');if(!savedRecipes.length){grid.innerHTML=`<div class="empty-state"><span>♡</span><h3>No saved recipes yet.</h3><p>When you find a dish you love, tap “Save recipe” to keep it here.</p><button class="primary" id="explore-recipes">Explore recipes <span>→</span></button></div>`;$('#explore-recipes').onclick=()=>route('discover');}else{grid.innerHTML=savedRecipes.map(recipeCard).join('');bindRecipeCards(grid);}const count=savedRecipes.length;$('#saved-count').textContent=count;$('#menu-saved-count').textContent=count;}
function updateSaveButton(){const isSaved=savedRecipes.includes(currentRecipe);const button=$('#save-recipe');button.classList.toggle('saved',isSaved);button.textContent=isSaved?'♥ Saved to your collection':'♡ Save recipe';}
function openRecipe(recipe){currentRecipe=recipe;$('#detail-title').textContent=recipe.title;$('#detail-summary').textContent=recipe.summary;$('#detail-time').textContent=recipe.time;const image=recipe.image||inspirationRecipes[recipes.indexOf(recipe)%inspirationRecipes.length].image;$('#detail-image').src=image;$('#detail-image').alt=recipe.title;$('#ingredient-list').innerHTML=(recipe.ingredients||[]).map(i=>`<label class="ingredient-row"><input type="checkbox"/><span>${escapeHtml(i)}</span></label>`).join('');$$('.ingredient-row input').forEach(input=>input.onchange=()=>input.parentElement.classList.toggle('checked',input.checked));$('#method-list').innerHTML=(recipe.steps||[]).map(s=>`<li>${escapeHtml(s)}</li>`).join('');$$('#method-list li').forEach(li=>li.onclick=()=>li.classList.toggle('done'));updateSaveButton();route('recipe');}
document.addEventListener('click',e=>{const link=e.target.closest('[data-route]');if(!link)return;e.preventDefault();route(link.dataset.route)});
document.addEventListener('click',e=>{const link=e.target.closest('[data-scroll]');if(!link)return;e.preventDefault();route('home');setTimeout(()=>$('#'+link.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'}),80)});
async function findRecipes(preference=''){const button=$('#find-recipes');button.disabled=true;button.textContent='Creating ingredient-only ideas…';try{const response=await fetch('/api/suggest-recipes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredients:pantry,preference})});const result=await readApiResponse(response);const available=new Set(pantry.map(item=>item.toLowerCase().replace(/\s*\([^)]*\)/g,'').trim()));recipes=(result.recipes||[]).filter(recipe=>recipe.ingredients.every(item=>available.has(item.toLowerCase().trim())));renderRecipes();$('#discovery-description').textContent=result.message||`Created only with ${pantry.slice(0,3).join(', ')}${pantry.length>3?' and more.':'.'}`;route('discover');}catch(error){toast(error.message||'Unable to reach OpenAI.');}finally{button.disabled=false;button.innerHTML='Find recipes <span>→</span>';}}
$('#home-prompt').onsubmit=e=>{e.preventDefault();const value=e.currentTarget.querySelector('input').value.trim();const preferenceOnly=/\b(quick|comfort|healthy|vegetarian|friends|special|under \d+|dinner)\b/i.test(value)&&!/^i have\b/i.test(value);if(value&&!preferenceOnly){pantry=value.replace(/^i have\s+/i,'').split(/,| and /).map(s=>s.trim()).filter(Boolean);renderPantry();}findRecipes(preferenceOnly?value:'')};
$$('[data-prompt]').forEach(button=>button.onclick=()=>{$('#home-prompt input').value=button.dataset.prompt;$('#home-prompt').requestSubmit()});
$('#add-ingredient').onclick=()=>{const input=$('#ingredient-input');const name=input.value.trim();if(name&&!pantry.some(x=>x.toLowerCase()===name.toLowerCase())){pantry.push(name);renderPantry();input.value=''}};
$('#ingredient-input').onkeydown=e=>{if(e.key==='Enter'){$('#add-ingredient').click();e.preventDefault()}};
$$('.suggestions button').forEach(b=>b.onclick=()=>{if(!pantry.includes(b.textContent)){pantry.push(b.textContent);renderPantry()}});
$('#find-recipes').onclick=()=>findRecipes();
$$('.filter').forEach(b=>b.onclick=()=>{ $$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const label=b.textContent;renderRecipes(label==='All recipes'?recipes:recipes.filter(r=>r.tag===label||(label==='Under 30 min'&&parseInt(r.time)<30)||(label==='One pan'&&r.tag==='One pan')))});
$('#save-recipe').onclick=()=>{const isSaved=savedRecipes.includes(currentRecipe);savedRecipes=isSaved?savedRecipes.filter(recipe=>recipe!==currentRecipe):[...savedRecipes,currentRecipe];updateSaveButton();renderSaved();toast(isSaved?'Recipe removed from saved.':'Recipe saved to your collection.')};
$('#cook-mode').onclick=()=>{const steps=$$('#method-list li');let first=[...steps].find(s=>!s.classList.contains('done'));if(first){first.classList.add('done');first.scrollIntoView({behavior:'smooth',block:'center'});toast('Step completed — keep going!')}else toast('Beautiful work — dinner is served!')};
const openModal=id=>{const modal=$('#'+id);modal.classList.add('open');modal.setAttribute('aria-hidden','false')};const closeModal=id=>{const modal=$('#'+id);modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
function setMenu(open){const menu=$('#header-menu'),button=$('#menu-button'),scrim=$('#menu-scrim');menu.classList.toggle('open',open);button.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close menu':'Open menu');scrim.classList.toggle('open',open);}
function closeMenu(){setMenu(false)}
$('#menu-button').onclick=()=>setMenu(!$('#header-menu').classList.contains('open'));$('#menu-scrim').onclick=closeMenu;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
$('#open-photo').onclick=()=>openModal('photo-modal');$('#close-photo').onclick=()=>closeModal('photo-modal');$('#close-results').onclick=()=>closeModal('results-modal');
function escapeHtml(value){return String(value||'').replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));}
function clampPercent(value){const number=Number(value);return Number.isFinite(number)?Math.min(100,Math.max(0,number)):50;}
async function readApiResponse(response){if(!(response.headers.get('content-type')||'').includes('application/json'))throw new Error('This app is being served by a static preview server. Stop it, run “npm start”, then open http://localhost:4173.');const data=await response.json();if(!response.ok)throw new Error(data.error||'The request could not be completed.');return data;}
function preparePhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/')){reject(new Error('Please choose a photo file.'));return;}const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const longestSide=Math.max(image.width,image.height),scale=Math.min(1,640/longestSide),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.68));};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('This photo format is not supported by your browser. Please use a JPG or PNG image.'));};image.src=url;});}
function renderPhotoAnalysis(analysis){const ingredients=Array.isArray(analysis.ingredients)?analysis.ingredients:[];const dish=analysis.dish||{};lastDish=dish.name||'';const recommendation=$('#dish-recommendation');recommendation.hidden=!dish.name;$('#dish-name').textContent=dish.name||'';$('#dish-description').textContent=dish.description||'';$('#dish-reason').textContent=dish.reason||'';const missing=Array.isArray(dish.missingIngredients)?dish.missingIngredients.filter(Boolean):[];$('#missing-ingredients').textContent=missing.length?`You may need: ${missing.join(', ')}.`:'You have the key ingredients for this dish.';$('#scan-results').innerHTML=ingredients.length?ingredients.map(ingredient=>{const focusX=clampPercent(ingredient.imageFocusX),focusY=clampPercent(ingredient.imageFocusY),name=escapeHtml(ingredient.name);return `<label class="scan-row"><span class="scan-thumb"><img src="${photoDataUrl}" alt="${name}" style="object-position:${focusX}% ${focusY}%"/></span><input class="scan-name" value="${name}"/><input class="scan-amount" value="${escapeHtml(ingredient.amount)}"/><input class="scan-include" type="checkbox" checked aria-label="Include ${name}"/></label>`}).join(''):'<p class="scan-empty">No recognizable ingredients were found in this photo. Try a clearer, well-lit image.</p>';const addButton=$('#add-scan-results');addButton.disabled=!ingredients.length;addButton.innerHTML=ingredients.length?'Add to pantry & find recipes <span>→</span>':'Try another photo';}
$('#photo-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;const analyzeButton=$('#analyze-photo');analyzeButton.disabled=true;analyzeButton.textContent='Preparing photo…';try{photoDataUrl=await preparePhoto(file);$('#photo-preview').src=photoDataUrl;$('#photo-dropzone').classList.add('has-image');analyzeButton.innerHTML='Ask ChatGPT to analyze <span>→</span>';analyzeButton.disabled=false;}catch(error){photoDataUrl='';$('#photo-dropzone').classList.remove('has-image');analyzeButton.innerHTML='Analyze ingredients <span>→</span>';toast(error.message);}};
$('#analyze-photo').onclick=async()=>{if(!photoDataUrl)return;const button=$('#analyze-photo');button.disabled=true;button.textContent='ChatGPT is analyzing your photo…';try{const response=await fetch('/api/analyze-pantry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageData:photoDataUrl})});const analysis=await readApiResponse(response);renderPhotoAnalysis(analysis);closeModal('photo-modal');openModal('results-modal');}catch(error){toast(error.message||'Unable to reach the photo analysis service. Start the app with npm start and try again.');}finally{button.disabled=false;button.innerHTML='Ask ChatGPT to analyze <span>→</span>';}};
$('#add-scan-results').onclick=()=>{const found=[...$$('.scan-row')].filter(row=>row.querySelector('.scan-include').checked).map(row=>row.querySelector('.scan-name').value.trim()).filter(Boolean);if(!found.length){closeModal('results-modal');openModal('photo-modal');return;}pantry=[...new Set([...pantry,...found])];renderPantry();closeModal('results-modal');findRecipes(lastDish?`Prioritize a dish like ${lastDish}.`:'');toast(`${found.length} ingredients added from your photo.`)};$$('.modal-backdrop').forEach(modal=>modal.onclick=e=>{if(e.target===modal)closeModal(modal.id)});
renderPantry();renderRecipes();renderSaved();
